### ISSUE TITLE
found error in network ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by tanz98** [cwise89/react-detect-offline#101]
Hello my friend found error in icanhazip ERR_NAME_NOT_RESOLVED , but just in his browser laptop. any idea to solve this issue?

she already clear cache, & try in another browser laptop like mozilla still get error like that and she open another web apps like youtube or google work perfectly. but in my laptop browser just work perfectly.

**Comment by cwise89** [comment]
I suggest your friend find another polling url. They are relying on the the old version of the default polling url.
