### ISSUE TITLE
Immediately ping

### ISSUE THREAD

**Issue by tonyhallett** [cwise89/react-detect-offline#43]
Currently the first ping is determined by the interval, so prior to that there could be an incomplete state

**Comment by chrisbolin** [comment]
totally agree @tonyhallett! i'll take a PR if you want to add that to `startPolling` - https://github.com/chrisbolin/react-detect-offline/blob/master/src/index.js#L142

**Comment by tonyhallett** [comment]
chris I have already implemented it in my own component ( needed react context and did not want multiple listeners and multiple pings in addition to [Don't listen to the online event when polling](https://github.com/chrisbolin/react-detect-offline/issues/44).  Was just bringing it to your attention

**Comment by FlxAlbroscheit** [comment]
I could provide a PR. However, should this become a default functionality or an option (pingImmediately [bool])?

**Comment by chrisbolin** [comment]
I think it should be standard behavior while polling. No need to put it behind a prop

**Comment by cwise89** [comment]
closing this, this feature will be added to v3 if no pr for this feature opened before then.
