### ISSUE TITLE
Online event is misleading - should always poll when "online"

### ISSUE THREAD

**Issue by GriffinSauce** [cwise89/react-detect-offline#45]
From [MDN](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/onLine):
> In Chrome and Safari, if the browser is not able to connect to a local area network (LAN) or a router, it is offline; all other conditions return true. So while you can assume that the browser is offline when it returns a false value, you cannot assume that a true value necessarily means that the browser can access the internet.

This is the most comprehensive implementation I've found but it still doesn't account for that fact.

True connectivity checking would:
- when "offline" return offline
- when "online", still check with ping and return that status

Really there are three statusses: offline | connected | online

**Comment by cwise89** [comment]
closing
