### ISSUE TITLE
Custom URL Pooling doesn't work

### ISSUE THREAD

**Issue by attiqeurrehman** [cwise89/react-detect-offline#53]
Hi,

I am having issue with custom URL pooling, following is the code:

```js
const polling = {
  enabled: true,
  url: "http://localhost/health",
  interval: 8000,
  timeout: 8000
};
```
and usage of it is:

```html
<Offline polling={polling}>
          <Alert color="danger">
            {<FontAwesomeIcon icon={faWifi} size="lg" />} Network is offline
          </Alert>
</Offline>
```
But it still goes to the https://ipv4.icanhazip.com/ instead of the custom URL added. Any idea? 

Version: 2.4.0

**Comment by psanders** [comment]
I'm having the same issue.

**Comment by chrisbolin** [comment]
@attiqeurrehman and @psanders sorry about this! PRs are welcome if you have time to look at it

**Comment by attiqeurrehman** [comment]
@chrisbolin I have checked again and found a typo in my code so mine is working. @psanders check the **getPollingConfig** in debugger. I hope you resolve your issue as well.

**Comment by ekynoxe** [comment]
I have the same issue and found that it happens if I switch my user agent to an unsupported one listed in https://github.com/chrisbolin/react-detect-offline/blob/master/src/index.js#L7

Why would the override not work on some user agents, but work on others?

**Comment by cwise89** [comment]
@ekynoxe I was looking into this issue just now. I changed my user-agent to `windows-chrome` and `windows-firefox`, but can't I get a repro. I'm going to close this for now, please let me know what specific user-agent is causing your problems and I'll re-open! Thanks for using our library :)
