### ISSUE TITLE
UnSupported User Agents Outdated?

### ISSUE THREAD

**Issue by subhendusethi** [cwise89/react-detect-offline#64]
https://github.com/chrisbolin/react-detect-offline/blob/c445f87ca50c3d015cdebf575a1a9433817dcd2a/src/index.js#L7

Windows Chrome has support navigator APIs, we should bump the version and update this line to remove Windows Chrome.

https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/onLine

**Comment by cwise89** [comment]
Hello @subhendusethi, I took a further look into this. I personally don't think Windows Chrome should be removed from the unsupported browser list. According to the docs:

> The update occurs when the user follows links or when a script requests a remote page. For example, the property should return false when users click links soon after they lose internet connection. 
~MDN

I can see how this would break some potential implementations of this library. Something to note with this browser feature is how they define "offline/online". Most browsers will have `window.navigator.onLine`, they do not follow the same definition.

Again, Thanks for the time investment here, I'm always happy to hear how we can make this better! :)
