### ISSUE TITLE
Possible issue with Safari on M1 

### ISSUE THREAD

**Issue by chrisbolin** [cwise89/react-detect-offline#73]
this bug blows my mind. it would mean that we'd need to re-enable the ping backup for safari (and maybe other browser on the M1).

https://twitter.com/P_Harrington83/status/1352624968044064769

**Comment by mildlygeeky** [comment]
Quick note here (I had observed the original issue on thedisconnect.co) - Safari 14, Big Sur, on M1 was what I was running. Offline mode detected properly with Chrome on the same site, same hardware. Would be good if someone else running an M1 could validate.

**Comment by chrisbolin** [comment]
@cwise89 we should have a quick "test site" that has both polling and non-polling components. that way we can have ppl test out on that and give us their results. 

e.g. in this case, i am guessing (hoping!) polling would still work on safari on an M1 mac

**Comment by cwise89** [comment]
I got my hands on an M1 this morning, and I cannot repro this. 

closing until there is a reliable repro
