### ISSUE TITLE
Access to XMLHttpRequest at 'https://www.swapi.tech/api/' from origin 'http://localhost:3030' has been blocked by CORS policy

### ISSUE THREAD

**Issue by cassiolacerda** [cwise89/react-detect-offline#84]
Hello!

In the version 2.4.0, the package used by default https://ipv4.icanhazip.com/ for polling and I have a project that works perfectly. In a new project, I use now version 2.4.3, and a cors problem is occurring. When I analised the source code, I found you change to new url: `https://www.swapi.tech/api/`.  Is there anything different that I need to implement in this new version?

**Comment by RonMichaeli** [comment]
+1

**Comment by MilesHart** [comment]
+1

This is concerning....

**Comment by MilesHart** [comment]
Ok, this is listed in the release notes.

https://github.com/cwise89/react-detect-offline/releases/tag/v2.4.3

Could you not use the current navigator address?

**Comment by rick427** [comment]
Am also encountering the same issue.

**Comment by cwise89** [comment]
If the default polling address is not working for you specifically, you must not rely on a default polling url. There are many factors in whether the default polling url will work for your implementation. Thank you @lluisemper for an awesome suggestion. 
Just to throw this out there, as it seems to be tripping lots of people up. Devolping on localhost against a server you can't enable CORS on, WILL cause problems and you don't have much control over that. After a quick google search, you will find plenty of workarounds.. I personally just spin up an NGROK server and hit that. This article has some other suggestions for y'all.
https://medium.com/swlh/avoiding-cors-errors-on-localhost-in-2020-5a656ed8cefa
