### ISSUE TITLE
`polling.url` should not have a default value

### ISSUE THREAD

**Issue by BrodaNoel** [cwise89/react-detect-offline#86]
I was checking the problem about CORS in the default `polling.url`.

I think this library should throw and error when `polling.url` is not defined, instead of having a default value.
Quite simple, and it will avoid killing third party servers.

**Comment by cwise89** [comment]
I really can't imagine that would go well for the thousands of people that rely on it.... Unless you would like to maintain the Issues that flood in.

**Comment by BrodaNoel** [comment]
How are you using semver?
I see currently it's on 2.4.4
Why did you change from 1.x to 2.x in the past? It had to be a breaking change.
Just release 3.x
'npm' is not going to switch to 3.x. Devs are going to have to do it manually. They are going to check here what's the breaking change and they are going to add a default value and that's all 🤷‍♂️
